import os

BACKEND_LOG_ENDPOINT = os.getenv("BACKEND_LOG_ENDPOINT")
BACKEND_API_KEY = os.getenv("BACKEND_API_KEY")

FEATURE_DB_URL = os.getenv("FEATURE_DB_URL")

BATCH_SIZE = 1000
KMEANS_K = 4
TRAIN_WINDOW_DAYS = 30